### ISSUE TITLE
Typoscript example

### ISSUE THREAD

**Issue by frikas** [jweiland-net/weather2#13]
I am using weather2 on the frontend top view, regardless wich page is loaded. I am not sure if I have included the plugin correctly. Please add a weather2 typoscript example  in the Documentation:

This is my solution, where I include "lib.weather" into my html template:

lib.weather2Plugin = RECORDS
lib.weather2Plugin {
    tables = tt_content
    source = 24
    dontCheckPid = 1
}

lib.weather = USER
lib.weather {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Weather2
    pluginName = Currentweather
    vendorName = JWeiland
    switchableControllerActions {
        CurrentWeather  {
            1 = show
        }
    }
    settings < plugin.tx_weather2.settings
    settings {
        startingPoint = 24
        persistence.storagePid = 32
    }
}

**Comment by pascal20997** [comment]
Hey frikas,
sorry for the late response but there was a lot to do. I´ll check that out and add an example to the documentation.
