### ISSUE TITLE
PHP Warning for getWindDirSection

### ISSUE THREAD

**Issue by fjaeker** [jweiland-net/weather2#14]
I've got the following Error:
PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, cannot access protected method JWeiland\Weather2\Domain\Model\CurrentWeather::getWindDirSection() in ../vendor/typo3fluid/fluid/src/Core/Variables/StandardVariableProvider.php line 321

The getWindDirSection function in CurrentWeather Model is the only one which is declared as 'protected'. If i declared it as 'public' it's fine.

**Comment by pascal20997** [comment]
You´re right. I have no idea why this method is declared as protected but it seems to be wrong. I´ll change that and publish a bug release. Thanks :)
