### ISSUE TITLE
Rain can be empty

### ISSUE THREAD

**Issue by Smove** [jweiland-net/weather2#15]
The openweather api can return an empty rain object for some requests.

This will cause a error because the content of this object is not checked before using array_shift at Classes/Task/OpenWeatherMapTask.php:251
`Argument 1 passed to JWeiland\Weather2\Domain\Model\CurrentWeather::setRainVolume() must be of the type integer, null given, called in /weather2/Classes/Task/OpenWeatherMapTask.php on line 251`

**Comment by hhaeb** [comment]
Same here since some days, maybe after an update of Typo3 from 8.7.27 to 8.7.28 on
Ubuntu 16.04

**Comment by Crontis** [comment]
We couldn't reproduce this problem but patched the issue. Hope it helps!

**Comment by hhaeb** [comment]
Update of 2.0.3 is NOT offered by repository. Manually update to 2.0.3 did help for me.

**Comment by pascal20997** [comment]
Thanks for the notice, just created the release and uploaded the new version to TER.
