### ISSUE TITLE
Error in reports module

### ISSUE THREAD

**Issue by RoxyHalliwell** [jweiland-net/weather2#20]
Thank you very much for the latest update. The upgrade wizard works fine. Unfortunately, I just discovered a new error in the reports module:

`Argument 4 passed to JWeiland\Weather2\Upgrade\RemoveLoggerFromSerializedTask87Upgrade::__construct() must be an instance of TYPO3\CMS\Install\Controller\Action\Tool\UpgradeWizard or null, instance of TYPO3\CMS\Install\Report\InstallStatusReport given, called in typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3975`

TYPO3 8.7.34
PHP 7.3.10
Latest extension version 2.0.4 (I updated from 2.0.3 and ran the upgrade wizard.)

**Comment by RoxyHalliwell** [comment]
Edit: Not fixed with version 2.0.5

**Comment by pascal20997** [comment]
Hey @RoxyHalliwell thank you very much for your issue ticket. I tested the latest version and was able to reproduce the error. I'll fix this in the next couple minutes and create a bug release for weather2.
