### ISSUE TITLE
Extension Key

### ISSUE THREAD

**Issue by ayacoo** [jweiland-net/weather2#24]
The TYPO3 extension package "jweiland/weather2", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by pascal20997** [comment]
Thank you very much :) I merged the PR
