### ISSUE TITLE
New dwd warn cell csv link

### ISSUE THREAD

**Issue by ayacoo** [jweiland-net/weather2#28]
https://www.dwd.de/DE/leistungen/opendata/help/warnungen/cap_warncellids_csv.csv?__blob=publicationFile&v=3

The URL could theoretically also be defined via the setting? How do you see that?

Advantage: You do not have to wait for an extension update.
Disadvantage: In the case of a new link update, the user does not notice this and loads from the old URL.

**Comment by pascal20997** [comment]
Thank you very much for all of your commits. There will be an update lets just replace the link for now and think about adding all API URLs to settings or e.g. the extension configuration later.
