### ISSUE TITLE
German Translation in wrong File

### ISSUE THREAD

**Issue by LMFC-Krisi** [jweiland-net/weather2#35]
Hello
In the locallang.xlf at Line 94 ist the following Code:

`<trans-unit id="tx_weather2_domain_model_weatheralert.preliminary_information">
				<source>Preliminary information</source>
				<target>Vorabinformation</target>`

I think it has to be moved to the de.locallang.xlf so that the translation will be done for German User.
Regards Michael

**Comment by froemken** [comment]
Hello @LMFC-Krisi 

thank you for that issue. I have updated the localization files in branch typo3_11_compatibility.

I will close this issue when I merge that branch into master

Stefan

**Comment by froemken** [comment]
I have just released version 4.0.0 which solved that issue.
