### ISSUE TITLE
Question for Update to Typo3 11

### ISSUE THREAD

**Issue by LMFC-Krisi** [jweiland-net/weather2#36]
Hello
Do you plan an Update for this Extension for Typo 3 Version 11
Regards Michael

**Comment by froemken** [comment]
Hello @LMFC-Krisi 

yes, of cause. Today is flex-friday and I just have created a new branch with current development: typo3_11_compatibility

Would be cool to see, if it works for you

Have a nice weekend

Stefan

**Comment by LMFC-Krisi** [comment]
Hello Stefan
Thanks for your work.
Actually i have no test environment with Typo3_11, so i can't test it. Perhaps someone else can test it.
If i have some time i will create a new Typo3_11 installation and test it. 
Regards Michael

**Comment by sfroemkenjw** [comment]
Hello @LMFC-Krisi 

I just see that a 11 compatible version is in TER. So, have fun using the new version

Stefan
