### ISSUE TITLE
Extension Caching

### ISSUE THREAD

**Issue by fjaeker** [jweiland-net/weather2#4]
I did not see that a own caching was implemented in the extension. This would be very helpful if the weather data is updated e.g. hourly by Scheduler Task

**Comment by pascal20997** [comment]
Hello @fjaeker,
currently the default TYPO3 page cache is used to cache the plugin. In later versions we´ll update our scheduler tasks to provide support for TCEMAIN.clearCacheCmd. Then you can use TCEMAIN.clearCacheCmd = <PageWhereThePluginIsDisplayed> to clear the cache of pages where the plugin is used automatically after weather data was updated.

**Comment by fjaeker** [comment]
Thanks for your feedback. The solution is unfortunately not useful for us, because we have weather informations often in the header on all pages (not just the home page) of a website. To delete the whole cache of a large hotel site on every hour is not a desired behaviour.
We have now written a separate extension that extends the weather2 with a caching mechanism via the caching framework.
Thanks for your work
