### ISSUE TITLE
"Create a new scheduler" not possible

### ISSUE THREAD

**Issue by adinetser** [jweiland-net/weather2#5]
.) Create a new scheduler with the Call openweathermap.org api selected with the scheduler module

TYPO3 8.7.8
weather2 1.2.0
static_info_tables .4.3

It's not possibel to create a new task "Call openweathermap.org api". After filling out all fields and try do save the new task there is no new task in the task list.

**Comment by pascal20997** [comment]
I just released version 1.2.1 via github and packagist (TER follows soon). Until this release wrong city names caused an general error message instead of a specific one. 

Can you please tell me the city and country you tried?

**Comment by adinetser** [comment]
Thank you,

i have updated the plugin to 1.2.1 but still the same problem.

I can't save the task! There are no error message.

I have tryed it width different cities and countries.

for example: Berlin - Germany or Wien - Austria

**Comment by pascal20997** [comment]
My colleague just tested weather2 with different TYPO3 installations. We think we found your problem. In TYPO3 8 there is no error message if the frequency for a recurring task is missing. Please fill in a frequency like 3600 to refresh weather data each 60 minutes or select "single" as task type.

**Comment by adinetser** [comment]
We found the problem!

Now we tested it on two different TYPO3 8.7.8 installation. One with "allow url fopen" one without.

It ony works wth "allow url fopen"

**Comment by pascal20997** [comment]
Thank you for your feedback, we´ll add a notice to the documentation or the tasks in coming releases to reduce the troubleshooting for this problem.
