### ISSUE TITLE
False Wind Speed

### ISSUE THREAD

**Issue by ValeriiaB93** [jweiland-net/weather2#52]
At our customer Homepage from Königsbach-Stein will be shown the Wind Speed about 289 m/s. On the page https://openweathermap.org/city/3206188 is it 2 m/s. 

The Code that we use:
<li><strong><f:translate key="tx_weather2_domain_model_currentweather.wind_speed_m_p_s" /></strong>: {currentWeather.windSpeedMPS} m/s <f:translate key="from" /> <f:translate key="tx_weather2_domain_model_currentweather.wind_readable_direction.{currentWeather.windDirSection}" /></li>

![Screenshot 18 3 2024 at 14 25](https://github.com/jweiland-net/weather2/assets/163864292/8f4d9dbc-530b-4534-adef-5b42f2985b5b)
![Screenshot 18 3 2024 at 14 26](https://github.com/jweiland-net/weather2/assets/163864292/bb201ccf-4b8a-47d6-8908-ad2860f6b506)

**Comment by nieslonybiz** [comment]
I confirm this issue for version 5.0.0. The same for my location.
The API call from openweathermap:
```
  "wind": {
    "speed": 8.23,
    "deg": 200,
    "gust": 13.38
  },
```
In the database of weather2 plugin:
```
   wind_speed_m_p_s: 200
 wind_direction_deg: 0
```

After a quick view, I think it results of this code:
weather2/Classes/Task/OpenWeatherMapTask.php (line 240ff):

```
        if (isset($responseClass->wind->speed)) {
            $weatherObjectArray['wind_speed_m_p_s'] = $responseClass->wind->speed;
        }
        if (isset($responseClass->wind->deg)) {
            $weatherObjectArray['wind_speed_m_p_s'] = $responseClass->wind->deg;
        }
```

**Comment by LMFC-Krisi** [comment]
Hallo zusammen
Ich kann dieses Problem auch reproduzieren. 
Typo3 12
PHP 8.2
weather2 5.0.0
Gruß Michael

**Comment by nieslonybiz** [comment]
Hi Michael,
please change line 244 in weather2/Classes/Task/OpenWeatherMapTask.php to:
`$weatherObjectArray['wind_direction_deg'] = $responseClass->wind->deg;`
and it works.

**Comment by ValeriiaB93** [comment]
> Hi Michael, please change line 244 in weather2/Classes/Task/OpenWeatherMapTask.php to: `$weatherObjectArray['wind_direction_deg'] = $responseClass->wind->deg;` and it works.

Thank you:)
