### ISSUE TITLE
Scheduler problem

### ISSUE THREAD

**Issue by piotrburda** [jweiland-net/weather2#6]
No changes in my TYPO3 installation, but suddenly on each scheduler run i have an error message:
Execution of task "Call openweathermap.org api (weather2)" failed with the following message: Task failed to execute successfully. Class: JWeiland\Weather2\Task\OpenWeatherMapTask, UID: 3

**Comment by seitenweiseUDO** [comment]
same problem here in 2 installations…

**Comment by pascal20997** [comment]
Which TYPO3 versions are you using and what city / country did you tried?

**Comment by seitenweiseUDO** [comment]
hi, we are using TYPO3 8.2.8 and tried bad oeynhausen and bielefeld.
i updated to version 1.2.1 of weather2 from github yesterday and everything is fine now…

**Comment by piotrburda** [comment]
TYPO3 7.6.23 weather2 1.2.0

**Comment by piotrburda** [comment]
update to 1.2.1 from github, did not resolve the issue:

Execution of task "Call openweathermap.org api (weather2)" failed with the following message: Task failed to execute successfully. Class: JWeiland\Weather2\Task\OpenWeatherMapTask, UID: 6
For: Livigno

**Comment by pascal20997** [comment]
Hello @piotrburda, Livigno Italy is working fine here using TYPO3 7.6 with PHP 7.1.
Is allow_url_fopen enabled in your PHP.ini file? That´s mandatory to fetch the weather information from openweathermap servers.
Otherwise please tell me your PHP version and/or send a screenshot of your scheduler task settings (without API-Key).

**Comment by piotrburda** [comment]
PHP: 7.1.10
allow_url_fopen  is ON
![weather1](https://user-images.githubusercontent.com/6623582/33451709-2747cf38-d610-11e7-9080-ef10139b8da9.png)
![weather2](https://user-images.githubusercontent.com/6623582/33451710-27678ed6-d610-11e7-9e06-bfcb5f41c145.png)

**Comment by pascal20997** [comment]
Ok the form looks good. So you can save the task but on execution you run into an error? If that´s the case, please execute it again and directly after go into your TYPO3 log and send me the weather2 (Scheduler) entries. If you don´t wanna send them here you can send it to projects@jweiland.net .

**Comment by pascal20997** [comment]
Hey @piotrburda do you solved the problem?
