### ISSUE TITLE
Country code

### ISSUE THREAD

**Issue by ymauray** [jweiland-net/weather2#7]
I have a problem with OpenWeatherMap's API : for the city "Lutry" in Switzerland (CHE) (q=Lutry,che), the API returns the weather for Lutry... in poland. To get the actual Swiss city's data, I need to call the API with "q=Lutry,ch".
Could there be an option to choose which country code to use ? Or just an optional textfield to put the country code by hand ? Or even, an empty option in the country dropdown, so I can put "lutry,ch" as the city name ?
Thanks.

**Comment by ymauray** [comment]
Sorry, I was too fast reporting this issue :-) It seems you fixed the country code issue but the version on the Typo3 Extension Repository is still 1.2.0 so it doesn't have it.
I'll use the github version, then.
Sorry for the noise !

**Comment by pascal20997** [comment]
Hello ymauray,
thank you for your noise. You reminded me to update weather2 in TER.
