### ISSUE TITLE
Also get vorabInformation from DWD Data

### ISSUE THREAD

**Issue by ghost** [jweiland-net/weather2#8]
DWD API provides "vorabInformation" for possible warnings in the future.
They can be fetched in Task/DeutscherWetterdienstTask.php -> handleResponse()  like the warnings with: $this->responseClass->vorabInformation and then displayed without checking the starttime.

**Comment by pascal20997** [comment]
Hey Olaf,
nice idea, I implemented the feature into version 2.0. Check it out.
Thanks
