### ISSUE TITLE
Scheduler crashes after installation of weather2

### ISSUE THREAD

**Issue by Pretorian112** [jweiland-net/weather2#9]
I am not able to place a scheduler task after installing weather2 extension.
The apache error-log shows the following: 
.../typo3conf/ext/weather2/Classes/Task/OpenWeatherMapTaskAdditionalFieldProvider.php on line 84

After disabling weather2 the scheduler works fine.

**Comment by Pretorian112** [comment]
This is, what the error log shows:

PHP Parse error:  syntax error, unexpected '[' in .../typo3conf/ext/weather2/Classes/Task/OpenWeatherMapTaskAdditionalFieldProvider.php on line 84

Again, any ideas?

**Comment by pascal20997** [comment]
Hey @Pretorian112, that´s a compatiblity issue with PHP versions older 5.4. I´ll fix this in the next few minutes.
Thank you for reporting that issue.

**Comment by pascal20997** [comment]
The new version 1.2.2 has been released on GitHub and Packagist. This version fixes the compatibility issue. If you downloaded weather2 via Extension Manager (TER) you have to wait a couple of days because I don´t manage that.
